name: Sales Service CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sales-service

jobs:
  provision:
    runs-on: ubuntu-latest
    outputs:
      ec2_instance_id: ${{ steps.set-id.outputs.INSTANCE_ID }}
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0" # Or your preferred version
          terraform_wrapper: false # <--- ADD THIS LINE

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform Init & Apply
        id: apply # Give this a name so we can reference it
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_github_repo: "InakiMedina/Sales" # TF_VAR_ prefix tells Terraform to map this to var.github_repo
          TF_VAR_github_token: ${{ secrets.GH_PAT }}
      - name: Export EC2 ID
        id: set-id
        run: echo "INSTANCE_ID=$(terraform output -raw ec2_instance_id)" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Tests
        # We set dummy env vars so the Cloud tests don't crash due to missing keys
        env:
          TICKETS_BUCKET: "test-bucket"
          SQS_URL: "https://test-queue"
        run: python -m pytest tests/

  deploy:
    needs: [provision, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Update EC2 via SSM
        run: |
          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids "${{ needs.provision.outputs.ec2_instance_id }}" \
          --parameters 'commands=[
            "docker stop sales-app || true",
            "docker rm sales-app || true",
            "docker run -d --name sales-app -p 80:8080 \
            -e TICKETS_BUCKET=${{ vars.TICKETS_BUCKET }} \
            -e SQS_URL=${{ vars.SQS_URL }} \
            -e NOTIFICATION_URL=${{ secrets.NOTIFICATION_LAMBDA_URL }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest"
          ]' \
          --region us-east-1